import { backendDomain } from "@/lib/constant/Domain";

export const APIDictionary = {
    setPassword: `${backendDomain}/api/v1/general/set-password`,
    leaveTypeList: `${backendDomain}/api/v1/leave/type`,
    list_of_leave_manager: `${backendDomain}/api/v1/manager/list-of-leave`,
    list_of_leave_employee: `${backendDomain}/api/v1/employee/list-of-leave`,
    leaveRequest: `${backendDomain}/api/v1/employee/leave/apply`,
    respondLeaveRequest: `${backendDomain}/api/v1/manager/respond-leave`,
    leaveTypeCreate: `${backendDomain}/api/v1/manager/leave-type/create`,
    leaveBalance:`${backendDomain}/api/v1/employee/leave-balance`,
    employee_list:`${backendDomain}/api/v1/manager/employee-list`,
    create_employee:`${backendDomain}/api/v1/employee/register`,
    checkIn:`${backendDomain}/api/v2/attendance/check-in`,
    checkOut:`${backendDomain}/api/v2/attendance/check-out`,
    todaySessions:`${backendDomain}/api/v2/attendance/session/`,
    attendanceHistory:`${backendDomain}/api/v2/attendance/history`,
    userProfile: (id: string) => `${backendDomain}/api/v2/user/${id}`,
    updateProfile: (id: string) => `${backendDomain}/api/v2/user/${id}`,
    Organization: `${backendDomain}/api/v2/organization`,
    Permission: `${backendDomain}/api/v2/permission`,
    role: `${backendDomain}/api/v2/role`,
    user: `${backendDomain}/api/v2/user`,
    role_permission: `${backendDomain}/api/v2/role-permission`,
    user_role: `${backendDomain}/api/v2/user-role`,
    leave_type: (id:string)=>`${backendDomain}/api/v2/leave-type/${id}`,
    get_all_org_leave_type: (org_id:string)=>`${backendDomain}/api/v2/leave-type/org/${org_id}`,
    leave_request: `${backendDomain}/api/v2/leave-request`,
    leave_balance: `${backendDomain}/api/v2/leave-balance`,
    attendance: `${backendDomain}/api/v2/attendance`,
    payroll: `${backendDomain}/api/v2/payroll`,
    events: `${backendDomain}/api/v2/events`,
    bank: `${backendDomain}/api/v2/bank-details`,
    payrollParameters: (userId: string) => `${backendDomain}/api/v2/payroll/parameters/${userId}`,
    notification: `${backendDomain}/api/v2/notification`,
    department: `${backendDomain}/api/v2/department`,
    dashboard: (userId: string) => `${backendDomain}/api/v2/screen/dashboard/${userId}`,
    get_payroll: (userId: string) => `${backendDomain}/api/v2/payroll/user/${userId}`,
    get_payroll_stats: (userId: string) => `${backendDomain}/api/v2/payroll/statistics/${userId}`,
    permission: `${backendDomain}/api/v2/permission`,
    holiday: `${backendDomain}/api/v2/holiday`,
    holiday_by_org: (orgId:string) => `${backendDomain}/api/v2/holiday/${orgId}`,
    holiday_type: `${backendDomain}/api/v2/holiday-type`,
    holiday_type_by_org: (orgId:string) => `${backendDomain}/api/v2/holiday-type/${orgId}`,
    OrganizationSettings: () => `${backendDomain}/api/v3/settings`,
    SalaryRecordExistence: (userId: string, month: number, year: number) => `${backendDomain}/api/v2/salary/user/${userId}/monthly/${month}/year/${year}`,
    permissionPreset: `${backendDomain}/api/v3/permission-preset`,

    // Bank Endpoints
    bankDetails: (userId: string) => `${backendDomain}/api/v2/bank-details/${userId}`,
    bankDetailsByUserId: (userId: string) => `${backendDomain}/api/v2/bank-details/user/${userId}`,
    allBankDetails: () => `${backendDomain}/api/v2/bank-details`,
};